### ISSUE TITLE
error running record_multi_step.py on new_collision

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#120]
(C:\Program Files\Anaconda3) C:\Users\Jedi\.scaii\git\SCAII\backends\sky-rts\demos>python record_multi_step.py
rts got Cfg
Possible reward types: {'took_damage', 'kill_bonus', 'friendly_kill', 'damaged_enemy', 'harmed_friend'}
Possible actions: {'actions': {'top_left': 4, 'bottom_right': 1, 'bottom_left': 3, 'top_right': 2}, 'desc': 'Use action.attack_quadrant(1-4) to select a quadrant to attack'}
Action description MoveList -- unit ID, command, and target
rts got ResetEnv
Collision event: Started(CollisionObjectHandle(0), CollisionObjectHandle(1)) :::  Data1: ColliderData { e: Entity(0, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(1, Generation(1)), owner: Some(Entity(0, Generation(1))), sensor: true }
Collision event: Started(CollisionObjectHandle(6), CollisionObjectHandle(7)) :::  Data1: ColliderData { e: Entity(6, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(7, Generation(1)), owner: Some(Entity(6, Generation(1))), sensor: true }
Collision event: Started(CollisionObjectHandle(8), CollisionObjectHandle(9)) :::  Data1: ColliderData { e: Entity(8, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(9, Generation(1)), owner: Some(Entity(8, Generation(1))), sensor: true }
Collision event: Started(CollisionObjectHandle(2), CollisionObjectHandle(3)) :::  Data1: ColliderData { e: Entity(2, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(3, Generation(1)), owner: Some(Entity(2, Generation(1))), sensor: true }
Collision event: Started(CollisionObjectHandle(4), CollisionObjectHandle(5)) :::  Data1: ColliderData { e: Entity(4, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(5, Generation(1)), owner: Some(Entity(4, Generation(1))), sensor: true }
recorderConfig pkt : ScaiiPacket { src: Endpoint { endpoint: Some(Agent(AgentEndpoint)) }, dest: Endpoint { endpoint: Some(Recorder(RecorderEndpoint)) }, specific_msg: Some(RecorderConfig(RecorderConfig { pkts: [ScaiiPacket { src: Endpoint { endpoint: Some(Agent(AgentEndpoint)) }, dest: Endpoint { endpoint: Some(Core(CoreEndpoint)) }, specific_msg: Some(Config(Cfg { which_module: Some(CoreCfg(CoreCfg { plugin_type: PluginType { plugin_type: Some(SkyRts(SkyRts)) } })) })) }, ScaiiPacket { src: Endpoint { endpoint: Some(Agent(AgentEndpoint)) }, dest: Endpoint { endpoint: Some(Backend(BackendEndpoint)) }, specific_msg: Some(Config(Cfg { which_module: Some(BackendCfg(BackendCfg { cfg_msg: Some([10, 12, 10, 10, 109, 117, 108, 116, 105, 95, 115, 116, 101, 112]), is_replay_mode: false })) })) }], overwrite: false, filepath: None })) }
...........persisting HEADER Header(ReplayHeader { configs: SerializedProtosScaiiPacket { data: [122, 56, 10, 18, 42, 6, 10, 4, 10, 2, 10, 0, 242, 1, 2, 26, 0, 250, 1, 2, 18, 0, 10, 32, 42, 20, 18, 18, 10, 14, 10, 12, 10, 10, 109, 117, 108, 116, 105, 95, 115, 116, 101, 112, 16, 0, 242, 1, 2, 10, 0, 250, 1, 2, 18, 0, 16, 0, 242, 1, 2, 50, 0, 250, 1, 2, 18, 0] } })
[0 1 2]
0
0
acting
RECORDER: action has expl_point?  YES
.............persisting KEYFRAME
Action caused rts.update()
Collision event: Started(CollisionObjectHandle(0), CollisionObjectHandle(2)) :::  Data1: ColliderData { e: Entity(0, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(2, Generation(1)), owner: None, sensor: false }
Collision event: Started(CollisionObjectHandle(1), CollisionObjectHandle(2)) :::  Data1: ColliderData { e: Entity(1, Generation(1)), owner: Some(Entity(0, Generation(1))), sensor: true } Data2: ColliderData { e: Entity(2, Generation(1)), owner: None, sensor: false }
Collision event: Started(CollisionObjectHandle(0), CollisionObjectHandle(3)) :::  Data1: ColliderData { e: Entity(0, Generation(1)), owner: None, sensor: false } Data2: ColliderData { e: Entity(3, Generation(1)), owner: Some(Entity(2, Generation(1))), sensor: true }
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
.............persisting KEYFRAME
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
RECORDER: action has expl_point?  NO
...........persisting DELTA
[0]
Traceback (most recent call last):
  File "record_multi_step.py", line 67, in <module>
    s = env.act(act, explanation=explanation)
  File "C:\Users\Jedi\.scaii\glue\python\scaii\env\__init__.py", line 302, in act
    resp = self._decode_handle_msg()
  File "C:\Users\Jedi\.scaii\glue\python\scaii\env\__init__.py", line 436, in _decode_handle_msg
    env_state=secret_state
  File "C:\Users\Jedi\.scaii\glue\python\scaii\env\sky_rts\env\state.py", line 36, in __init__
    faction_ids, np.unique(faction_ids)).astype(np.float)[:, :, 1:]
ValueError: could not broadcast input array from shape (40,40,0) into shape (40,40,2)

**Comment by LinearZoetrope** [comment]
This is an issue that already could happen, albeit rarely. It occurs in the current state decoding in Python when only one faction is on the screen. It's likely that what happened was we got the rare (0.3^4, specifically) chance that all friendly units were friendly on a new decision step.

This will naturally be fixed by #106.
