### ISSUE TITLE
low >= high Rng.gen_range error

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#4]
It looks like the fix to the Pos problem exposed/caused another issue as console output in the browser suggests I'm not receiving the first viz packet, where I was prior.  I set BACKTRACE=1 and captured the following trace.  I ran it a bunch of times and seemed to happen regardless of the seed value.
```
Sending a VizInit message
Protocol: We'll send you a ScaiiPacket delta, you apply it and send us your entity info (one ScaiiPacket in a MultiMessage).
Connection will be closed after a random number of ticks between 10 and 20, or with anerror message on desynchronization or incorrect response.
Sending a VizInit ScaiiPacket, no response expected
Sending first volley of entities to initialize list
thread 'main' panicked at 'Rng.gen_range called with low >= high', C:\Users\Jed Irvine\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.3.16\src\lib.rs:503:8
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<&str>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: rand::Rng::gen_range<rand::XorShiftRng,usize>
             at .\<panic macros>:3
   6: rpc_viz::update_entities<rand::XorShiftRng>
             at .\src\main.rs:422
   7: rpc_viz::test_loop<rand::XorShiftRng>
             at .\src\main.rs:475
   8: rpc_viz::test_viz_client
             at .\src\main.rs:504
   9: rpc_viz::main
             at .\src\main.rs:509
  10: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  11: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  12: main
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  14: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\Jed Irvine\exact\SCAII\target\debug\rpc-viz.exe configuration.toml` (exit code: 101)
```

**Comment by Jragonmiris** [comment]
Note, you can use three tildes like so:
\`\`\` 
blah blah
\`\`\`

```
blah blah
```

To do code blocks and make the stack trace a little more readable.

**Comment by jedirv** [comment]
got it.

**Comment by Jragonmiris** [comment]
Fixed, I just didn't know `low` couldn't be equal to `high`, but I guess it makes sense since it's an exclusive range.
