### ISSUE TITLE
another range related issue

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#5]
```
Sending a VizInit message
Protocol: We'll send you a ScaiiPacket delta, you apply it and send us your entity info (one ScaiiPacket in a MultiMessage).
Connection will be closed after a random number of ticks between 10 and 20, or with anerror message on desynchronization or incorrect response.
Sending a VizInit ScaiiPacket, no response expected
Sending first volley of entities to initialize list
thread 'main' panicked at 'internal error: entered unreachable code: 99 > 100?', src\entity\mod.rs:397:8
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   6: rpc_viz::entity::IdEntity::create_update<rand::XorShiftRng>
             at .\src\entity\mod.rs:397
   7: rpc_viz::entity::EntityUpdate::apply_and_make_proto<rand::XorShiftRng>
             at .\src\entity\mod.rs:426
   8: rpc_viz::update_entities<rand::XorShiftRng>
             at .\src\main.rs:430
   9: rpc_viz::test_loop<rand::XorShiftRng>
             at .\src\main.rs:460
  10: rpc_viz::test_viz_client
             at .\src\main.rs:489
  11: rpc_viz::main
             at .\src\main.rs:494
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  16: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\Jed Irvine\exact\SCAII\target\debug\rpc-viz.exe configuration.toml` (exit code: 101)
```

**Comment by jedirv** [comment]
woops - I had a print statement commented out and uncommenting reveals that I am in fact getting viz packets.  Perhaps this is how the backend is complaining when it gets the wrong state for the second return packet (which will happen until I develop further).  I'll check into it

**Comment by Jragonmiris** [comment]
Got it
