### ISSUE TITLE
still a problem with length of error being sent 

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#7]
I rebased in the fix for the determinism issue and still see this:
```
Sending a VizInit message
Protocol: We'll send you a ScaiiPacket delta, you apply it and send us your entity info (one ScaiiPacket in a MultiMessage).
Connection will be closed after a random number of ticks between 10 and 20, or with anerror message on desynchronization or incorrect response.
Sending a VizInit ScaiiPacket, no response expected
Sending first volley of entities to initialize list
thread 'main' panicked at 'Could not send error closure: DataFrameError("Control frame length too long")', src\libcore\result.rs:860:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:497
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:92
   8: core::result::unwrap_failed<websocket::result::WebSocketError>
             at C:\projects\rust\src\libcore\macros.rs:41
   9: core::result::Result<(), websocket::result::WebSocketError>::expect<(),websocket::result::WebSocketError>
             at C:\projects\rust\src\libcore\result.rs:762
  10: rpc_viz::verify_scaii_packet::{{closure}}
             at .\src\main.rs:226
  11: core::ops::function::impls::{{impl}}::call_once<(&scaii_defs::protos::Entity),closure>
             at C:\projects\rust\src\libcore\ops\function.rs:191
  12: core::option::Option<&scaii_defs::protos::Entity>::map<&scaii_defs::protos::Entity,rpc_viz::entity::IdEntity,&mut closure>
             at C:\projects\rust\src\libcore\option.rs:398
  13: core::iter::{{impl}}::next<rpc_viz::entity::IdEntity,core::slice::Iter<scaii_defs::protos::Entity>,closure>
             at C:\projects\rust\src\libcore\iter\mod.rs:1073
  14: alloc::vec::{{impl}}::spec_extend<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1825
  15: alloc::vec::{{impl}}::from_iter<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1808
  16: alloc::vec::{{impl}}::from_iter<rpc_viz::entity::IdEntity,core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>>
             at C:\projects\rust\src\liballoc\vec.rs:1695
  17: core::iter::iterator::Iterator::collect<core::iter::Map<core::slice::Iter<scaii_defs::protos::Entity>, closure>,alloc::vec::Vec<rpc_viz::entity::IdEntity>>
             at C:\projects\rust\src\libcore\iter\iterator.rs:1303
  18: rpc_viz::verify_scaii_packet
             at .\src\main.rs:217
  19: rpc_viz::test_loop<rand::XorShiftRng>
             at .\src\main.rs:478
  20: rpc_viz::test_viz_client
             at .\src\main.rs:500
  21: rpc_viz::main
             at .\src\main.rs:505
  22: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  23: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  24: main
  25: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  26: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\Jed Irvine\exact\SCAII\target\debug\rpc-viz.exe configuration.toml` (exit code: 101)
```

**Comment by Jragonmiris** [comment]
Got it
